name: Main to Production Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 # this is important for git-auto-commit-action to work

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable

      - name: Remove default Chromium
        run: sudo apt purge chromium-browser

      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Run resume.py
        run: python .github/workflows/resume.py

      - name: Set up git user
        run: |
          git config --local user.email "noreply@zayedkherani.com"
          git config --local user.name "GitHub Action"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push to production branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: $(git log -1 --pretty=%B)
          branch: production
          commit_options: "--no-verify --signoff"
          repository: .
          commit_user_name: GitHub Action
          commit_user_email: noreply@zayedkherani.com
          commit_author: GitHub Action <noreply@zayedkherani.com>
