name: Verified Commits Workflow (production)

on:
  push:
    branches:
      - production

jobs:
  verified_commit_check_production:
    runs-on: ubuntu-latest

    steps:
      - name: Check for unverified commits
        uses: nadock/verified_commits_check@v1